# Generated by Django 4.2.3 on 2023-08-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0006_payment_payment_intent_id_payment_payment_method_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время обновления'),
        ),
    ]
